<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;

/**
 * Implements hook_theme ().
 */
function custom_event_theme() {
  return [
    'events_liste' => [
      'variables' => [
        'events' => [],
      ],
    ],
  ];
}
/**
 * Implements hook_cron().
 */
function custom_event_cron() {

  // Current date white datetime storage format.
  $now = new DrupalDateTime();
  $now->setTimezone(new \DateTimeZone(DateTimeItemInterface::STORAGE_TIMEZONE));
  $now = $now->format(DateTimeItemInterface::DATETIME_STORAGE_FORMAT);
  $events_id = \Drupal::service('custom_event.service_event')->getEvents(NULL, $now, NULL, FALSE, TRUE);
  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('event_unpublish_queue');
  foreach ($events_id as $event_id) {
    $queue->createItem($event_id);
  }

}